language: node_js
node_js:
  - 12
git:
  quiet: true
  autocrlf: input
branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+\.\d+.*$/
script:
  - yarn --frozen-lockfile --silent
  - yarn lint
  - yarn build
  - yarn test
before_deploy:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - npm install -g serverless@1.79.0
deploy:
  - provider: script
    script: yarn --frozen-lockfile --silent && yarn deploy:staging && yarn build:reset
    on:
      branch: develop
  - provider: script
    script: yarn --frozen-lockfile --silent && yarn deploy:prod && yarn build:reset
    on:
      branch: master
      tags: true
